# Generated by Django 5.1.7 on 2025-04-02 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('strength', 'Fuerza'), ('endurance', 'Resistencia'), ('speed', 'Velocidad'), ('flexibility', 'Flexibilidad'), ('agility', 'Agilidad'), ('balance', 'Equilibrio'), ('coordination', 'Coordinación')], max_length=100)),
                ('description', models.TextField()),
                ('unit', models.CharField(choices=[('seconds', 'Segundos'), ('minutes', 'Minutos'), ('meters', 'Metros'), ('centimeters', 'Centímetros'), ('kilograms', 'Kilogramos'), ('repetitions', 'Repeticiones'), ('score', 'Puntuación')], max_length=20)),
                ('higher_is_better', models.BooleanField(default=True, help_text='¿Un valor más alto representa un mejor resultado?')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('discipline', models.CharField(choices=[('athletics', 'Athletics'), ('soccer', 'Soccer'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('rugby', 'Rugby'), ('american_football', 'American Football'), ('swimming', 'Swimming'), ('taekwondo', 'Taekwondo'), ('flag_football', 'Flag Football'), ('futsal', 'Futsal'), ('beach_volleyball', 'Beach Volleyball'), ('table_tennis', 'Table Tennis'), ('martial_arts', 'Martial Arts'), ('boxing', 'Boxing'), ('physical_conditioning', 'Physical Conditioning'), ('gap_training', 'GAP (Glutes, Abs, Legs)'), ('investigation', 'Investigation')], max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('evaluator', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.evaluationsession')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.test')),
            ],
            options={
                'unique_together': {('athlete', 'test', 'session')},
            },
        ),
    ]
