# Generated by Django 5.2 on 2025-04-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
