# Generated by Django 5.2 on 2025-05-19 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_alter_customuser_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='coach',
        ),
        migrations.AddField(
            model_name='customuser',
            name='coach',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'coach'}, null=True, related_name='athletes', to=settings.AUTH_USER_MODEL),
        ),
    ]
