# Generated by Django 5.2 on 2025-05-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_remove_customuser_coach_customuser_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='coach',
        ),
        migrations.AddField(
            model_name='customuser',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to=settings.AUTH_USER_MODEL),
        ),
    ]
